window.trans = {
 "Give-and-Go": "Быстрый старт",
 "with": "с",
 "and": "и",
 "in": "в",
 "vs.": "против",
 "ruby library": "Ruby библиотека",
 "query language": "Язык запросов",
 "hard to pronounce": "трудно произносить",
 "easier": "легче",
 "Database Driver": "Драйвер базы данных",
 "Abstraction Layer": "Слой абстракции", // обертка?
 "\"Don't go through life without goals\"": "\"Не иди по жизни без цели\"",
 "Advantages": "Преимущества",
 "Types": "Типы данных",
 "Queries": "Запросы",
 "Other Features": "Другие особенности",
 "Array": "Массив",
 "Eliminate": "Избавьтесь от",
 "JOINs": "JOINов",
 "Up to": "В",
 "20x": "20 раз",
 "No": "Нет",
 "Referential Integrity": "Целостности Ссылочных Данных",
 "15x": "15 раз",
 "\"You can always get someone to do your thinking for you\"": "\"Вы всегда можете заставить кого-то думать за вас\"",
 "Indexes": "Индексов",
 "Faster": "быстрее",
 "Tradeoffs": "Альтернативы",
 "Not For Much Longer": "Ненамного дольше", // ибо наречие без противопоставления с союзом
 "Replace": "Замените",
 "(mostly)": "(где можно)",
 "columns": "столбцы",
 "Boolean": "Булевый тип", // ибо словарь
 "Schemaless": "Без схемы",
 "foreign key": "внешний ключ",
 "string": "строка",
 "Entity": "Объект",
 "Attribute": "Атрибут",
 "Value": "Значение",
 "Example:": "Пример:",
 "for strings only": "только для строк",
 "for everything?": "для всего?",
 "Exception Class": "Класс ошибки",
 "Message": "Сообщение",
 "Backtrace": "Трассировка",
 "Request Environment": "Окружение запроса",
 "Request Params": "Параметры запроса",
 "Session Variables": "Переменные сессии",
 "Document Databases with Schemas": "Документ-ориентированные БД со схемой", // ибо словарь
 "Composite Types": "Составные типы",
 "Range Types": "Диапазонные типы",
 "Benefits?": "Преимущества?",
 "Exclusion Constraints": "Исключение ограничений",
 "Insert successful": "Insert сработал!",
 "Error raised!": "Возникла ошибка!",
 "Review": "Повтор",
 "\"Forget about style; worry about results\"": "\"Забудьте о стиле; беспокоиться о результатах\"",
 "Graph Database": "Графовая база данных",
 "Nested Sets": "Вложенные множества",
 "Window Functions": "Оконные функции",
 "Category": "Категория",
 "Name": "Название",
 "Price": "Цена",
 "Elbow Pad": "Налокотник",
 "Shin Guard": "Щиток",
 "Helmet": "Шлем",
 "Gloves": "Перчатки",
 "Jersey": "Свитер",
 "Socks": "Носки",
 "Mouth Guard": "Капа",
 "Stick": "Клюшка",
 "Skates": "Коньки",
 "Puck": "Шайба",
 "Difference": "Разность",
 "Row Number": "Номер строки",
 "Limited Eager Loading": "Ограниченная жадная загрузка",
 "Full Text Search": "Полнотекстовый поиск",
 "english": "russian",
 "example text": "бла бла бла",
 "joined HC CSKA Moscow": "выступает за ЦСКА Москва",
 "\"There are only two hard things in Computer Science: cache invalidation and naming things.\"": "\"Есть только две сложные вещи в Computer Science: инвалидация кэша и названия переменных.\"",
 "Prepared Transactions": "Подготовленные транзакции",
 "Your code here": "Ваш код здесь",
 "Procedural Languages": "Процедурные языки",
 "Anonymous Functions: DO": "Анонимные функции: DO",
 "\"A good hockey player plays where the puck is. A great hockey player plays where the puck is going to be.\"": "\"Хорошие игроки находятся там, где шайба. Великие – там, где она будет.\"",
 "Other hockey photos": "Другие фото хоккея",
 "photo": "фото"
};
